# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

cache_root_dir: /usr/scratch2/dolent1/gitlabci/buildcache/huettern/snitch

artifacts:
  python:
    inputs:
    - .gitlab-ci.d/build-python.sh
    outputs:
    - install/python

  occamy_vcu128:
    inputs:
    - .gitlab-ci.d/occamy_cfg_fpga.sh
    # all occamy sources
    - hw/system/occamy/src
    # Other RTL sources
    - hw/ip
    - hw/vendor
    outputs:
    - hw/system/occamy/fpga/occamy_vcu128

  br-hrv-vcu128:
    inputs:
    - hw/system/occamy/fpga/Makefile
    - hw/system/occamy/fpga/br2_external/configs
    - hw/system/occamy/fpga/br2_external/rootfs
    - hw/system/occamy/fpga/br2_external/patch
    - hw/system/occamy/fpga/br2_external/external.desc
    - hw/system/occamy/fpga/br2_external/external.mk
    - hw/system/occamy/fpga/br2_external/Config.in
    outputs:
    - hw/system/occamy/fpga/br2_external/install
    - hw/system/occamy/fpga/output/br-hrv-vcu128/images

  occamy-vcu128-bootrom:
    inputs:
    - hw/system/occamy/fpga/bootrom/occamy.dts
    - hw/system/occamy/fpga/bootrom/src
    - hw/system/occamy/fpga/bootrom/Makefile
    outputs:
    - hw/system/occamy/fpga/bootrom/bootrom-spl.bin
    - hw/system/occamy/fpga/bootrom/bootrom-spl.coe
    - hw/system/occamy/fpga/bootrom/bootrom-spl.dump
    - hw/system/occamy/fpga/bootrom/bootrom-spl.elf
